In [1]:
# COSC 522 UTK
# Group 5 - Final Project
# Corey Lovette, Noah Archer, Stephen Williams and Tyler Herndon

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [7]:
# Read the data from the CSV file
df = pd.read_csv('Fraud.csv')

# Display basic information about the dataset
print("Dataset Size: ", df.size);
print("Dataset Shape: ", df.shape);
print("Dataset Columns: ", df.columns);
print("Dataset Data Types: ", df.dtypes);
print("Missing Values by Column: ", df.isnull().sum());
print("Total Frauds and Non-Frauds: ", df['isFraud'].value_counts());

# Display a few of the records
df.tail();

Dataset Size:  69988820
Dataset Shape:  (6362620, 11)
Dataset Columns:  Index(['step', 'type', 'amount', 'nameOrig', 'oldbalanceOrg', 'newbalanceOrig',
       'nameDest', 'oldbalanceDest', 'newbalanceDest', 'isFraud',
       'isFlaggedFraud'],
      dtype='object')
Dataset Data Types:  step                int64
type               object
amount            float64
nameOrig           object
oldbalanceOrg     float64
newbalanceOrig    float64
nameDest           object
oldbalanceDest    float64
newbalanceDest    float64
isFraud             int64
isFlaggedFraud      int64
dtype: object
Missing Values by Column:  step              0
type              0
amount            0
nameOrig          0
oldbalanceOrg     0
newbalanceOrig    0
nameDest          0
oldbalanceDest    0
newbalanceDest    0
isFraud           0
isFlaggedFraud    0
dtype: int64
Total Frauds and Non-Frauds:  isFraud
0    6354407
1       8213
Name: count, dtype: int64

In [8]:
df.tail()

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
6362615,743,CASH_OUT,339682.13,C786484425,339682.13,0.0,C776919290,0.00,339682.13,1,0
6362616,743,TRANSFER,6311409.28,C1529008245,6311409.28,0.0,C1881841831,0.00,0.00,1,0
6362617,743,CASH_OUT,6311409.28,C1162922333,6311409.28,0.0,C1365125890,68488.84,6379898.11,1,0
6362618,743,TRANSFER,850002.52,C1685995037,850002.52,0.0,C2080388513,0.00,0.00,1,0
6362619,743,CASH_OUT,850002.52,C1280323807,850002.52,0.0,C873221189,6510099.11,7360101.63,1,0

In [12]:
from sklearn.model_selection import train_test_split

x = df.drop(["isFraud", "isFlaggedFraud"], axis=1)
y = df["isFraud"]